#!/usr/bin/env ruby  
  
require File.expand_path('../../config/application', __FILE__)  
Rails.application.require_environment!  
  
class ResqueWorkerDaemon < DaemonSpawn::Base  
  def start(args)  
    @worker = Resque::Worker.new('data_loader')
    @worker.work  
  end  
  
  def stop  
    @worker.try(:shutdown)  
  end  
end  
  
ResqueWorkerDaemon.spawn!({
  :processes => 1, # プロセス数の指定
  :working_dir => Rails.root,  
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'work_daemon.pid'),  
  :log_file => File.join(Rails.root, 'log', 'work_daemon.log'),  
  :sync_log => true,  
  :singleton => true
})  